import { useTranslation } from "react-i18next";

export function useExerciseMetadataLabels() {
  const { t } = useTranslation();

  const bodyParts: Record<string, string> = {
    back: t("exercise.bodyPart.back", "back"),
    cardio: t("exercise.bodyPart.cardio", "cardio"),
    chest: t("exercise.bodyPart.chest", "chest"),
    "lower arms": t("exercise.bodyPart.lowerArms", "lower arms"),
    "lower legs": t("exercise.bodyPart.lowerLegs", "lower legs"),
    neck: t("exercise.bodyPart.neck", "neck"),
    shoulders: t("exercise.bodyPart.shoulders", "shoulders"),
    "upper arms": t("exercise.bodyPart.upperArms", "upper arms"),
    "upper legs": t("exercise.bodyPart.upperLegs", "upper legs"),
    waist: t("exercise.bodyPart.waist", "waist"),
  };

  const equipment: Record<string, string> = {
    "Any equipment": t("exercise.equipment.anyEquipment", "Any equipment"),
    assisted: t("exercise.equipment.assisted", "assisted"),
    band: t("exercise.equipment.band", "band"),
    barbell: t("exercise.equipment.barbell", "barbell"),
    bench: t("exercise.equipment.bench", "bench"),
    "body weight": t("exercise.equipment.bodyWeight", "body weight"),
    "bosu ball": t("exercise.equipment.bosuBall", "bosu ball"),
    cable: t("exercise.equipment.cable", "cable"),
    custom: t("customExercise.custom", "custom"),
    dumbbell: t("exercise.equipment.dumbbell", "dumbbell"),
    "elliptical machine": t("exercise.equipment.ellipticalMachine", "elliptical machine"),
    Equipment: t("exercise.equipment.equipment", "Equipment"),
    "ez barbell": t("exercise.equipment.ezBarbell", "ez barbell"),
    hammer: t("exercise.equipment.hammer", "hammer"),
    kettlebell: t("exercise.equipment.kettlebell", "kettlebell"),
    "leverage machine": t("exercise.equipment.leverageMachine", "leverage machine"),
    "medicine ball": t("exercise.equipment.medicineBall", "medicine ball"),
    "olympic barbell": t("exercise.equipment.olympicBarbell", "olympic barbell"),
    Recovery: t("exercise.equipment.recovery", "Recovery"),
    "resistance band": t("exercise.equipment.resistanceBand", "resistance band"),
    roller: t("exercise.equipment.roller", "roller"),
    rope: t("exercise.equipment.rope", "rope"),
    "skierg machine": t("exercise.equipment.skiergMachine", "skierg machine"),
    "sled machine": t("exercise.equipment.sledMachine", "sled machine"),
    "smith machine": t("exercise.equipment.smithMachine", "smith machine"),
    "squat rack": t("exercise.equipment.squatRack", "squat rack"),
    "stability ball": t("exercise.equipment.stabilityBall", "stability ball"),
    "stationary bike": t("exercise.equipment.stationaryBike", "stationary bike"),
    "stepmill machine": t("exercise.equipment.stepmillMachine", "stepmill machine"),
    Strength: t("exercise.equipment.strength", "Strength"),
    tire: t("exercise.equipment.tire", "tire"),
    "trap bar": t("exercise.equipment.trapBar", "trap bar"),
    "upper body ergometer": t("exercise.equipment.upperBodyErgometer", "upper body ergometer"),
    weighted: t("exercise.equipment.weighted", "weighted"),
    "wheel roller": t("exercise.equipment.wheelRoller", "wheel roller"),
  };

  const muscles: Record<string, string> = {
    abdominals: t("exercise.muscle.abdominals", "abdominals"),
    abductors: t("exercise.muscle.abductors", "abductors"),
    abs: t("exercise.muscle.abs", "abs"),
    adductors: t("exercise.muscle.adductors", "adductors"),
    ankles: t("exercise.muscle.ankles", "ankles"),
    "ankle stabilizers": t("exercise.muscle.ankleStabilizers", "ankle stabilizers"),
    biceps: t("exercise.muscle.biceps", "biceps"),
    brachialis: t("exercise.muscle.brachialis", "brachialis"),
    calves: t("exercise.muscle.calves", "calves"),
    "cardiovascular system": t("exercise.muscle.cardiovascularSystem", "cardiovascular system"),
    core: t("exercise.muscle.core", "core"),
    deltoids: t("exercise.muscle.deltoids", "deltoids"),
    delts: t("exercise.muscle.delts", "delts"),
    feet: t("exercise.muscle.feet", "feet"),
    forearms: t("exercise.muscle.forearms", "forearms"),
    glutes: t("exercise.muscle.glutes", "glutes"),
    "grip muscles": t("exercise.muscle.gripMuscles", "grip muscles"),
    groin: t("exercise.muscle.groin", "groin"),
    hamstrings: t("exercise.muscle.hamstrings", "hamstrings"),
    hands: t("exercise.muscle.hands", "hands"),
    "hip flexors": t("exercise.muscle.hipFlexors", "hip flexors"),
    "inner thighs": t("exercise.muscle.innerThighs", "inner thighs"),
    "latissimus dorsi": t("exercise.muscle.latissimusDorsi", "latissimus dorsi"),
    lats: t("exercise.muscle.lats", "lats"),
    "levator scapulae": t("exercise.muscle.levatorScapulae", "levator scapulae"),
    "lower abs": t("exercise.muscle.lowerAbs", "lower abs"),
    "lower back": t("exercise.muscle.lowerBack", "lower back"),
    obliques: t("exercise.muscle.obliques", "obliques"),
    pectorals: t("exercise.muscle.pectorals", "pectorals"),
    quadriceps: t("exercise.muscle.quadriceps", "quadriceps"),
    quads: t("exercise.muscle.quads", "quads"),
    "rear deltoids": t("exercise.muscle.rearDeltoids", "rear deltoids"),
    rhomboids: t("exercise.muscle.rhomboids", "rhomboids"),
    "rotator cuff": t("exercise.muscle.rotatorCuff", "rotator cuff"),
    "serratus anterior": t("exercise.muscle.serratusAnterior", "serratus anterior"),
    shins: t("exercise.muscle.shins", "shins"),
    soleus: t("exercise.muscle.soleus", "soleus"),
    spine: t("exercise.muscle.spine", "spine"),
    sternocleidomastoid: t("exercise.muscle.sternocleidomastoid", "sternocleidomastoid"),
    trapezius: t("exercise.muscle.trapezius", "trapezius"),
    traps: t("exercise.muscle.traps", "traps"),
    triceps: t("exercise.muscle.triceps", "triceps"),
    "upper back": t("exercise.muscle.upperBack", "upper back"),
    "upper chest": t("exercise.muscle.upperChest", "upper chest"),
    "wrist extensors": t("exercise.muscle.wristExtensors", "wrist extensors"),
    "wrist flexors": t("exercise.muscle.wristFlexors", "wrist flexors"),
    wrists: t("exercise.muscle.wrists", "wrists"),
  };

  return {
    bodyPart: (value: string) => bodyParts[value] ?? value,
    equipment: (value: string) => equipment[value] ?? value,
    muscle: (value: string) => muscles[value] ?? value,
  };
}
